# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hubcarapp', '0002_customer_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='item_images/')),
                ('price', models.IntegerField(default=0)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hubcarapp.Garage')),
            ],
        ),
    ]
